---
- name: Copying files to remote server
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: Copy files
    copy:
      src: /home/ansibleControlNode/Downloads/aws_login.pem
      dest: /home/ansibleHosts/
