---
- name: Set Password for User
  hosts: all
  become: true
  become_user: root

  tasks:
  - name: Set Password
    user:
      name: admin
      update_password: always
      password: "{{'pass@123' | password_hash('sha512')}}"
