---
- name: Uninstall Nginx on Remote Hosts
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped

    - name: uninstall nginx using apt-get
      shell:
        cmd: |
          sudo apt-get remove nginx nginx-common -y &&
          sudo apt-get purge nginx nginx-common -y &&
          sudo apt-get autoremove -y
      ignore_errors: yes
