---
# tasks file for nginx_setup
- name: Install Nginx
  apt:
    name: "{{ nginx_package_name }}"
    state: present
  become: true

- name: Place custom HTML File
  copy:
    src: index.html 
    dest: "{{ html_file_path }}"
  become: true

- name: Start the service
  service:
    name: "{{ nginx_package_name  }}"
    state: started
    enabled: yes
  become: true
